### ISSUE TITLE
design the user panel. so that we can get the info of the user when he gets clicked

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/the-peace-pledge#11]

**Comment by abdulhannanali** [comment]
we'll use mongo db object id in order to display his information in /user/:id

**Comment by sudheesh001** [comment]
Since its fixed and structured information, how about using ORM systems like `Sequelize` with MariaDB / MySQL.

Probably a good chance for you to also learn about ORMs, MongoDB is also not an issue if you're planning to finish this task and move ahead with others.

**Comment by sudheesh001** [comment]
http://docs.sequelizejs.com/en/latest/ Here's the link

**Comment by abdulhannanali** [comment]
Hi Mentor ! I looked into Sequelize before starting this project and realized this is very similar to the ODM Mongoose for MongoDB. MongooseJS provides all the schema, validations, models and default value stuff using MongoDB. I am using Mongoose as my ODM. It's quite popular in **Node** community.  Also mongolab is providing me with free DB Hosting upto 500MB for mongodb. What do you think about [Mongoose](http://mongoosejs.com)? Should I keep using it or switch to Sequelize?  This is my current code for User model [user model](../models/user.js) and my [user controller](../controllers/user.controller.js)

**Comment by abdulhannanali** [comment]
File link correction for user model https://github.com/abdulhannanali/the-peace-pledge/blob/master/models/user.js

**Comment by sudheesh001** [comment]
No problem I just wanted you to go ahead with any ORMs, Mongoose is a fine choice.

**Comment by abdulhannanali** [comment]
Thanks mentor :+1:  Yeah mongoose is great

**Comment by abdulhannanali** [comment]
I have to implement this yet

**Comment by abdulhannanali** [comment]
@sudheesh001 I have implemented the /user/:id route. You can see the site at https://damp-ridge-2114.herokuapp.com

**Comment by abdulhannanali** [comment]
thanks for the help

**Comment by sudheesh001** [comment]
Very well done. I am really impressed with your work @abdulhannanali

**Comment by abdulhannanali** [comment]
@sudheesh001 thanks for the complement awesome mentor. thank you for your kind help too
