### ISSUE TITLE
image for a person

### ISSUE THREAD

**Issue by abdulhannanali** [abdulhannanali/the-peace-pledge#9]
an optional image for a person if she/he wants to upload one. image will be uploaded to imgur

**Comment by abdulhannanali** [comment]
maybe use gravatar for it

**Comment by sudheesh001** [comment]
Use gravatar ! :smile: I was about to say that

**Comment by abdulhannanali** [comment]
haha thanks mentor @sudheesh001 ease of use of gravatar makes it awesome.

**Comment by abdulhannanali** [comment]
@sudheesh001 thanks for your help. I have implemented gravatar in it
